"""
Property-based test for JSON-RPC 2.0 structural validity of MCP server responses.

Feature: guided-diagnosis-multi-agent, Property 2: Validité structurelle JSON-RPC 2.0

**Validates: Requirements 2.4, 3.1**

Property 2: For ALL MCP method calls (tools/list, tools/call, resources/list,
resources/read, prompts/list, prompts/get) with ANY valid parameters, the
JSON-RPC 2.0 response generated by the BaseMCPServer must contain the fields
`jsonrpc` (value "2.0") and `id` matching the request id, and either `result`
(for success) or `error` (for errors). If `error`, it must have `code` (int)
and `message` (str).
"""
from __future__ import annotations

import asyncio
import json

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st
from httpx import ASGITransport, AsyncClient

from backend.agents.mcp_servers.base_server import BaseMCPServer


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def parse_sse_response(text: str) -> dict:
    """Extract the JSON-RPC 2.0 payload from an SSE ``data:`` line."""
    for line in text.strip().split("\n"):
        if line.startswith("data:"):
            return json.loads(line[len("data:"):].strip())
    raise ValueError("No data line found in SSE response")


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


async def _echo_handler(arguments: dict) -> dict:
    """Simple tool handler that echoes its arguments."""
    return {"echo": arguments}


@pytest.fixture(autouse=True)
def _reset_sse_app_status():
    """Reset sse-starlette's AppStatus event so it binds to the current loop."""
    from sse_starlette.sse import AppStatus
    AppStatus.should_exit_event = asyncio.Event()
    yield


@pytest.fixture()
def server() -> BaseMCPServer:
    """Create a BaseMCPServer with one tool, one resource, and one prompt registered."""
    srv = BaseMCPServer(server_name="test_jsonrpc", port=9997)
    srv.register_tool(
        "test_tool", "A test tool", {"type": "object"}, handler=_echo_handler,
    )
    srv.register_resource(
        "test://resource", "Test Resource", "A test resource", "text/plain",
    )
    srv.register_prompt(
        "test_prompt", "A test prompt", [{"name": "arg1", "required": True}],
    )
    return srv


# ---------------------------------------------------------------------------
# Hypothesis strategies
# ---------------------------------------------------------------------------

# Methods and their valid params
_MCP_METHODS = [
    "tools/list",
    "tools/call",
    "resources/list",
    "resources/read",
    "prompts/list",
    "prompts/get",
]


def _params_for_method(method: str) -> dict:
    """Return valid params for a given MCP method."""
    if method == "tools/list":
        return {}
    if method == "tools/call":
        return {"name": "test_tool", "arguments": {"key": "value"}}
    if method == "resources/list":
        return {}
    if method == "resources/read":
        return {"uri": "test://resource"}
    if method == "prompts/list":
        return {}
    if method == "prompts/get":
        return {"name": "test_prompt"}
    return {}


_st_method = st.sampled_from(_MCP_METHODS)
_st_request_id = st.integers(min_value=1, max_value=10000)


# ---------------------------------------------------------------------------
# Feature: guided-diagnosis-multi-agent, Property 2: Validité structurelle JSON-RPC 2.0
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
@settings(max_examples=100, suppress_health_check=[HealthCheck.too_slow, HealthCheck.function_scoped_fixture])
@given(method=_st_method, request_id=_st_request_id)
async def test_property_2_jsonrpc_structural_validity(
    server: BaseMCPServer,
    method: str,
    request_id: int,
) -> None:
    """Validates: Requirements 2.4, 3.1

    For any MCP method call with valid parameters, the JSON-RPC 2.0 response
    must contain `jsonrpc` == "2.0", `id` matching the request id, and either
    a `result` key (success) or an `error` key with `code` (int) and `message`
    (str).
    """
    params = _params_for_method(method)
    request_body = {
        "jsonrpc": "2.0",
        "method": method,
        "params": params,
        "id": request_id,
    }

    transport = ASGITransport(app=server.app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        resp = await client.post("/rpc", json=request_body)

    payload = parse_sse_response(resp.text)

    # jsonrpc field must be "2.0"
    assert payload.get("jsonrpc") == "2.0", (
        f"Expected jsonrpc='2.0', got {payload.get('jsonrpc')!r}"
    )

    # id must match the request id
    assert payload.get("id") == request_id, (
        f"Expected id={request_id}, got {payload.get('id')!r}"
    )

    # Must have either 'result' or 'error', but not both
    has_result = "result" in payload
    has_error = "error" in payload
    assert has_result or has_error, (
        f"Response must contain 'result' or 'error', got keys: {list(payload.keys())}"
    )
    assert not (has_result and has_error), (
        "Response must not contain both 'result' and 'error'"
    )

    # If error, validate its structure
    if has_error:
        error = payload["error"]
        assert isinstance(error, dict), f"'error' must be a dict, got {type(error)}"
        assert isinstance(error.get("code"), int), (
            f"'error.code' must be an int, got {type(error.get('code'))}"
        )
        assert isinstance(error.get("message"), str), (
            f"'error.message' must be a str, got {type(error.get('message'))}"
        )
